site_name: Winston
theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  icon:
    logo: material/robot-excited-outline
  features:
    - toc.integrate
    - navigation.sections
    
